### PR TITLE
Update minimum node versions

### PR DESCRIPTION
**Pull request by liquidnya**
### Checklist

- [x] Have you followed the guidelines in our Contributing document?
- [ ] Have you run `eslint` on the code and resolved any errors?
- [ ] Have you run `npm test` and all tests are passing?
- [ ] Have you added new tests for any new functions created?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you updated CHANGELOG.md to add your changed under the `[Unreleased]` heading?

### Description

When running `npm run build` with node versions `16.14.0`, `16.15.0`, and `16.16.0` then the following error occurs:

```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/nya/projects/fluid-queue/glob.js' imported from /home/nya/projects/fluid-queue/
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:437:11)
    at moduleResolve (node:internal/modules/esm/resolve:1009:10)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at resolve (file:///home/nya/projects/fluid-queue/node_modules/@swc-node/register/esm/esm.mjs:78:12)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Benefits

Building the project works with node version `16.17.0`.

### Potential drawbacks

Someone could still use node version `16.14.0`, but I could not find a different fix.

### CODE REVIEW

**Comment by liquidnya** [comment]
Should we add the minimum node version to the CHANGELOG.md?

**Comment by liquidnya** [comment]
Build also does not work with node versions `17.0.0`, `17.4.0`, `17.6.0`, `17.8.0`, `17.9.1`, so basically does not work with node version 17 at all (which is okay since version 17 is end of life).
Does not work with the following versions either `18.1.0`, `18.5.0`. (Build works with `18.6.0`)
Also note that version 19 is already end of life, but has security support until 2023-06-01. (Build works with `19.0.0`)
Also I think the queue also works with `20.0.0`.

Should we add version 20 to the github workflows?

**Comment by demize** [comment]
Honestly, we should probably just target the latest LTS version and test on current. Right now that'd be 18.16.0 and 20.1.0. Update the workflow to both test and lint on 18.x and 20.x, and bump our minimum version to the lowest 18.x version it runs on (but mention, probably in the README, that we're aiming to target the latest LTS release).

We should be encouraging people to stay updated, rather than let them stay on EOL or discontinued versions. Makes our jobs easier, makes their lives more secure.

**Comment by liquidnya** [comment]
Sounds good to me!

**Comment by liquidnya** [comment]
I updated to versions 18 and 20 for the tests, and linting; and updated the docker build to use version 20.
Also updated typescript configuration to target node 18.

**Comment by demize** [comment]
I'm going to update the branch protection rules to check for the results as of this PR now, then I think I'm gonna come back and approve these changes.

**Review by demize — APPROVED** [review]
Yep, LGTM. If you don't merge this in I probably will, just so I can rebase on it.
